services:
  frontend:
    image: 661041596293.dkr.ecr.eu-north-1.amazonaws.com/frontend:latest
    stdin_open: true
    ports:
      - "5173:80"
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - assimetria-app

  backend:
    image: 661041596293.dkr.ecr.eu-north-1.amazonaws.com/backend:latest
    ports:
      - "4000:4000"
    restart: always
    environment:
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - HF_TOKEN=${HF_TOKEN}
    networks:
      - assimetria-app

networks:
  assimetria-app:
    driver: bridge
